### ISSUE TITLE
support for NSO4.5.1

### ISSUE THREAD

**Issue by mano2soft** [NSO-developer/pioneer#1]
Hi NSO-developers, 

Does the support for NSO4.5 also support 4.5.1, I get the below error when i make.
I am using nso-4.5.1.linux.x86_64.signed.bin.

(nso) [root@bit-etv-serv1 src]# make
PYTHONPATH=../python:$PYTHONPATH python ../python/pioneer/action.py
Traceback (most recent call last):
  File "../python/pioneer/action.py", line 30, in <module>
    import pioneer.namespaces.pioneer_ns as ns
  File "/root/nso/run/packages/pioneer/python/pioneer/__init__.py", line 3, in <module>
    from action import Action
  File "/root/nso/run/packages/pioneer/python/pioneer/action.py", line 39, in <module>
    import op.config_op
  File "/root/nso/run/packages/pioneer/python/pioneer/op/config_op.py", line 15, in <module>
    import netconf_op
ModuleNotFoundError: No module named 'netconf_op'
make: *** [py] Error 1

Thanks,
Manoj

**Comment by sstrollo** [comment]
Weird, works for me (`netconf_op` is part of pioneer, seems it can't be found?). What does the following three commands say:

`ncs --version`

`python --version`

`ls ../python/pioneer/op`

/Sebastian

**Comment by mano2soft** [comment]
Hi Sebastian,

Please find the details
(nso) [root@bit src]# ncs --version
4.5.1
(nso) [root@bit src]# python --version
Python 3.6.3
(nso) [root@bit src]# ls ../python/pioneer/op
__init__.py  __pycache__  base_op.py  config_op.py  ex.py  log_op.py  netconf_op.py  netconf_trace.py  yang_op.py
(nso) [root@bit src]# 
+++++++++++++++++++++
I also found StringIO and cStringIO modules are deprecated due to this netconf_op is missing, it will fail netconf_trace also. 
Reference:https://stackoverflow.com/questions/28200366/python-3-4-0-email-package-install-importerror-no-module-named-cstringio 

>>> import netconf_op
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/nso/run/packages/pioneer/python/pioneer/op/netconf_op.py", line 9, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

Thanks,
Manoj

**Comment by mano2soft** [comment]
NSO-4.4.4 worked with python2.7. 
Need enhancement for  python3.0 onwards

**Comment by sstrollo** [comment]
Thanks Manoj,

Yes, it does seem like a Python 3 issue (it worked for me, but with Python 2.7), I don't know if @janlindblad has tested with that, I'll have to defer to him, as I don't know the details of this package.

/Sebstian

**Comment by novakmi** [comment]
Initial porting to Python3 was done, see PR:
https://github.com/NSO-developer/pioneer/pull/6
